/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;

import java.lang.reflect.Method;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bavic
 */
public class form_Compra extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    //Variables
    private static ArrayList<Object> listaProductos = Menu.getListaProductos();
    private static ArrayList<String[]> listaCompra = new ArrayList<String[]>();
    private Object productoTemp = null;
    DefaultTableModel modelTab = new DefaultTableModel();

    public form_Compra() {

        initComponents();
        IniciarTabla();
        lbl_AVISO.setVisible(false);
    }

    private void IniciarTabla() {
        String[] Titulos = {"ID", "NOMBRE", "CANTIDAD", "VALOR C/U"};
        modelTab = new DefaultTableModel(Titulos, 0);
        tabla_Factura.setModel(modelTab);

    }

    private void ActualizarFactura() {
        double subTotal = 0;
        double iva = 0;
        double total = 0;
        for (int i = 0; i < listaCompra.size(); i++) {
            double precio = Double.parseDouble(listaCompra.get(i)[3]);
            double cant = Double.parseDouble(listaCompra.get(i)[2]);
            subTotal = subTotal + (precio * cant);

        }
        iva = subTotal * 0.12;
        total = subTotal + iva;

        lbl_Subtotal.setText(String.format("%.2f", subTotal));
        lbl_Iva.setText(String.format("%.2f", iva));
        lbl_Total.setText(String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Iva = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        btn_EliminarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_Stock = new javax.swing.JLabel();
        lbl_AVISO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_Producto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        lbl_Valor_cu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Factura = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Añadir = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        cb_TipoProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Nuevo = new javax.swing.JButton();
        lbl_Subtotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mI_Inicio = new javax.swing.JMenuItem();
        meIt_Venta = new javax.swing.JMenuItem();
        mI_Registro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra");
        setBackground(new java.awt.Color(51, 204, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lbl_Iva.setText("0 $");

        lbl_Total.setText("0 $");

        btn_EliminarProducto.setText("Eliminar Producto");
        btn_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarProductoActionPerformed(evt);
            }
        });

        jLabel9.setText("Stock:");

        lbl_Stock.setText("0");

        lbl_AVISO.setForeground(new java.awt.Color(255, 51, 51));
        lbl_AVISO.setText("Ingrese una ID válida");

        jLabel6.setText("Iva 12%:");

        jLabel7.setText("Total:");

        cb_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ProductoActionPerformed(evt);
            }
        });

        jLabel11.setText("Producto: ");

        lbl_Valor_cu.setText("0 $");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("VENTA DE PRODUCTO");

        tabla_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_Factura);

        jLabel8.setText("BUSCAR PRO ID:");

        jLabel2.setText("Cantidad:");

        jLabel3.setText("TIpo de Producto:");

        btn_Añadir.setText("Añadir");
        btn_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AñadirActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar:");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        cb_TipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comestible", "Utensilio", "Oficina", "Industrial" }));
        cb_TipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TipoProductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor c/u: ");

        jLabel5.setText("Subtotal: ");

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        lbl_Subtotal.setText("0 $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_AVISO, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cb_TipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cb_Producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl_Valor_cu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btn_Añadir)
                                                    .addGap(33, 33, 33)
                                                    .addComponent(btn_Nuevo))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btn_Buscar)
                                                    .addGap(12, 12, 12)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_EliminarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_AVISO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_TipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(lbl_Valor_cu)
                    .addComponent(cb_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbl_Stock)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Añadir)
                    .addComponent(btn_Nuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Iva)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Total)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addComponent(btn_EliminarProducto))
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        mI_Inicio.setText("Inicio");
        mI_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_InicioActionPerformed(evt);
            }
        });
        jMenu1.add(mI_Inicio);

        meIt_Venta.setText("Venta");
        meIt_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meIt_VentaActionPerformed(evt);
            }
        });
        jMenu1.add(meIt_Venta);

        mI_Registro.setText("Registro");
        mI_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mI_RegistroActionPerformed(evt);
            }
        });
        jMenu1.add(mI_Registro);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        //
        try {
            boolean exist = false;
            int id = Integer.parseInt(txt_Id.getText());
            int id2 ;
            for (Object producto : listaProductos) {
                //Guarda el id de cada producto de la lista en id2
                Method metodoGetID = producto.getClass().getMethod("getId");
                id2 = (int) metodoGetID.invoke(producto);
                if (id == id2) {
                    exist = true;
                    //Guarda los datos del objeto encontrado y para ingresarlos en la interfaz
                    String nombreProducto = (String) producto.getClass().getMethod("getNombre").invoke(producto);
                    int stock = (int) producto.getClass().getMethod("getStock").invoke(producto);
                    double valor = (double) producto.getClass().getMethod("getValor").invoke(producto);
                    String tipoProducto = (String) producto.getClass().getMethod("getTipoProducto").invoke(producto);
                    //los introduce en la interfaz
                    cb_TipoProducto.setSelectedItem(tipoProducto);

                    lbl_Valor_cu.setText(String.valueOf(valor));
                    lbl_Stock.setText(String.valueOf(stock));
                    //Borra todos los componentes del cb_producto y añade el introducido por la ID
                    cb_Producto.removeAllItems();
                    cb_Producto.addItem(nombreProducto);
                    cb_Producto.setSelectedItem(producto);
                    //Guarda el producto encontrado en una variable para su próximo uso
                    productoTemp = producto;
                    break;
                }
            }
            //Si id2 == -1 significa que no existe La Id buscada por lo que envia un aviso
            if (!exist) {
                lbl_AVISO.setText("ID No encontrada");
                lbl_AVISO.setVisible(true);
            } else {

                lbl_AVISO.setVisible(false);
            }
        } catch (Exception e) {
            System.out.println("Formulario de compra error: " + e);
            lbl_AVISO.setText("Ingrese una ID válida");
            lbl_AVISO.setVisible(true);
        }


    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void meIt_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meIt_VentaActionPerformed

    }//GEN-LAST:event_meIt_VentaActionPerformed

    private void mI_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_RegistroActionPerformed
        form_Registro men = new form_Registro();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mI_RegistroActionPerformed

    private void cb_TipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TipoProductoActionPerformed
//Añade los productos correspondientes al cb_producto
        try {
            String tipoProd = cb_TipoProducto.getSelectedItem().toString();
            String tipoProd2 = "";
            cb_Producto.removeAllItems();
            for (Object producto : listaProductos) {
                //Guarda el tipo de cada producto de la lista en tipoProd2
                Method metodoGetID = producto.getClass().getMethod("getTipoProducto");
                tipoProd2 = (String) metodoGetID.invoke(producto);
                if (tipoProd.equals(tipoProd2)) {
                    String nombreProducto = (String) producto.getClass().getMethod("getNombre").invoke(producto);
                    int stock = (int) producto.getClass().getMethod("getStock").invoke(producto);
                    //Comprueba que haya stock para vender
                    if (stock > 0) {
                        //añade los productos correspondientes al mismo tipo seleccionado

                        cb_Producto.addItem(nombreProducto);
                    }

                }
            }

        } catch (Exception e) {
            System.out.println("cb_TipoProd Error: " + e + " LINE: " + e.getStackTrace()[0].getLineNumber());
            lbl_AVISO.setText("Ingrese una ID válida");
            lbl_AVISO.setVisible(true);
        }

    }//GEN-LAST:event_cb_TipoProductoActionPerformed

    private void cb_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ProductoActionPerformed
        try {
            if (cb_Producto.getSelectedItem() != null) {
                String nom1 = cb_Producto.getSelectedItem().toString();
                String nom2 = "";
                //Hace  la busqueda por nombre parar rellenar los campos faltantes
                for (Object producto : listaProductos) {

                    Method metodoGetNombre = producto.getClass().getMethod("getNombre");
                    nom2 = (String) metodoGetNombre.invoke(producto);
                    if (nom1.equals(nom2)) {
                        //Guarda los datos del objeto encontrado y para ingresarlos en la interfaz

                        int id = (int) producto.getClass().getMethod("getId").invoke(producto);
                        int stock = (int) producto.getClass().getMethod("getStock").invoke(producto);
                        double valor = (double) producto.getClass().getMethod("getValor").invoke(producto);

                        //los introduce en la interfaz
                        txt_Id.setText(String.valueOf(id));
                        lbl_Valor_cu.setText(String.valueOf(valor));
                        lbl_Stock.setText(String.valueOf(stock));
                        //Guarda el producto encontrado en una variable para su próximo uso
                        productoTemp = producto;
                        break;
                    }
                }
            }

        } catch (Exception e) {
            System.out.println("cb_Producto error: " + e + " LINE: " + e.getStackTrace()[0].getLineNumber());

        }

    }//GEN-LAST:event_cb_ProductoActionPerformed

    private void btn_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AñadirActionPerformed

        try {
            Object producto = productoTemp;

            //  Comprueba que haya suficiente Stock del producto
            int stock = (int) producto.getClass().getMethod("getStock").invoke(producto);
            int cantidad = Integer.parseInt(txt_Cantidad.getText());
            boolean exist = false;
            if (cantidad <= stock) {

                //Guarda los datos del producto
                Method metodoGetID = producto.getClass().getMethod("getId");
                int id = (int) metodoGetID.invoke(producto);
                String nombreProducto = (String) producto.getClass().getMethod("getNombre").invoke(producto);
                double valor = (double) producto.getClass().getMethod("getValor").invoke(producto);
                String[] nuevoProducto = new String[4];

                nuevoProducto[0] = String.valueOf(id);
                nuevoProducto[1] = nombreProducto;
                nuevoProducto[2] = txt_Cantidad.getText();
                nuevoProducto[3] = String.valueOf(valor);
                //Comprueba si el objeto seleccionado ya existe en la lista de la compra y lo actualiza

                for (int i = 0; i < listaCompra.size(); i++) {

                    String[] prod = listaCompra.get(i);
                    int id2 = Integer.parseInt(prod[0]);

                    if (id == id2) {

                        modelTab.setValueAt((Integer.parseInt(modelTab.getValueAt(i, 2).toString()) + cantidad), i, 2);
                        tabla_Factura.setModel(modelTab);
                        listaCompra.get(i)[2] = String.valueOf(Integer.parseInt(listaCompra.get(i)[2]) + cantidad);
                        exist = true;
                        break;
                    }

                }

                //Añade los datos del producto a la tabla y a la listadeCompra    
                if (!exist) {
                    modelTab.addRow(nuevoProducto);
                    listaCompra.add(nuevoProducto);
                }

                //Resta la cantidad seleccionada del stock del producto y lo actualiza a la lista 
                producto.getClass().getMethod("setStock", int.class).invoke(producto, (stock - cantidad));
                //Actualiza el stock en la interfaz
                lbl_Stock.setText(String.valueOf((int) producto.getClass().getMethod("getStock").invoke(producto)));

                //Actualiza el total a pagar los precios:
                ActualizarFactura();

                lbl_AVISO.setVisible(false);
            } else {
                lbl_AVISO.setText("No hay Suficiente Stock");
                lbl_AVISO.setVisible(true);
            }

        } catch (NumberFormatException e) {
            System.out.println(e);
            lbl_AVISO.setText("LLene los campos Correctamente");
            lbl_AVISO.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);

        }


    }//GEN-LAST:event_btn_AñadirActionPerformed

    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        txt_Cantidad.setText("");
        txt_Id.setText("");
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void mI_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mI_InicioActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mI_InicioActionPerformed

    private void btn_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarProductoActionPerformed
        int fila = tabla_Factura.getSelectedRow();

        if (fila != -1) {
            try {
                int cantidad = Integer.parseInt(listaCompra.get(fila)[2]);
                
                int id = Integer.parseInt(listaCompra.get(fila)[0]);
                int id2;
                //Busca el objeto en la lista de productos y le duevelve la cantidad a su stock
                for (Object producto : listaProductos) {

                    Method metodoGetID = producto.getClass().getMethod("getId");
                    id2 = (int) metodoGetID.invoke(producto);
                    if (id == id2) {
                        
                        int stock = (int) producto.getClass().getMethod("getStock").invoke(producto);
                        producto.getClass().getMethod("setStock", int.class).invoke(producto, (stock + cantidad));
                        break;
                    }
                }

                //Actualiza los datos de la lista y la tabla
                listaCompra.remove(fila);
                modelTab.removeRow(fila);

                //actualiza los precios
                ActualizarFactura();
            } catch (Exception e) {
                System.out.println("btn_Eliminar" + e);

            }
        }


    }//GEN-LAST:event_btn_EliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_Compra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_Compra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_Compra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_Compra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Añadir;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_EliminarProducto;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JComboBox<String> cb_Producto;
    private javax.swing.JComboBox<String> cb_TipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_AVISO;
    private javax.swing.JLabel lbl_Iva;
    private javax.swing.JLabel lbl_Stock;
    private javax.swing.JLabel lbl_Subtotal;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_Valor_cu;
    private javax.swing.JMenuItem mI_Inicio;
    private javax.swing.JMenuItem mI_Registro;
    private javax.swing.JMenuItem meIt_Venta;
    private javax.swing.JTable tabla_Factura;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Id;
    // End of variables declaration//GEN-END:variables
}
