/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_factura;

/**
 *
 * @author bavic
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
                lbl_Adv.setVisible(false);
    }

    public boolean camposLLenos() {
        if (txt_Cantidad.getText().equals("") || txt_Nombre.getText().equals("") || txt_Valor.getText().equals("") || txt_descuento.getText().equals("")) {
           lbl_Adv.setVisible(true);
            return false;
        } else {
            lbl_Adv.setVisible(false);
            return true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Nombre = new javax.swing.JTextField();
        txt_Valor = new javax.swing.JTextField();
        txt_Cantidad = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_subtotal = new javax.swing.JButton();
        btn_TotalConIVA = new javax.swing.JButton();
        TotalConDescuento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_ValorAPagar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_Adv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Valor:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Descuento: %");

        btn_subtotal.setText("Subtotal");
        btn_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subtotalActionPerformed(evt);
            }
        });

        btn_TotalConIVA.setText("Total con IVA 12%");
        btn_TotalConIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TotalConIVAActionPerformed(evt);
            }
        });

        TotalConDescuento.setText("Total con descuento");
        TotalConDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalConDescuentoActionPerformed(evt);
            }
        });

        jLabel5.setText("VALOR A PAGAR: ");

        lbl_ValorAPagar.setBackground(new java.awt.Color(51, 255, 204));
        lbl_ValorAPagar.setText("0");
        lbl_ValorAPagar.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Cálculo de presupuesto en material de construcción");

        lbl_Adv.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Adv.setText("*LLene todos los campos*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_subtotal)
                        .addGap(61, 61, 61)
                        .addComponent(btn_TotalConIVA)
                        .addGap(38, 38, 38)
                        .addComponent(TotalConDescuento))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(41, 41, 41)
                                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbl_Adv, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_ValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Adv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_ValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_subtotal)
                    .addComponent(btn_TotalConIVA)
                    .addComponent(TotalConDescuento))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subtotalActionPerformed
        if (camposLLenos()) {
            String nombre = txt_Nombre.getText();
            int cantidad = Integer.parseInt(txt_Cantidad.getText());
            double descuento = Double.parseDouble(txt_descuento.getText());
            double valor = Double.parseDouble(txt_Valor.getText());
            Material men = new Material(nombre, cantidad, valor, descuento);

            lbl_ValorAPagar.setText(String.valueOf(men.getSubTotal()));
        }

    }//GEN-LAST:event_btn_subtotalActionPerformed

    private void btn_TotalConIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TotalConIVAActionPerformed
        if (camposLLenos()) {
            String nombre = txt_Nombre.getText();
            int cantidad = Integer.parseInt(txt_Cantidad.getText());
            double descuento = Double.parseDouble(txt_descuento.getText());
            double valor = Double.parseDouble(txt_Valor.getText());
            Material men = new Material(nombre, cantidad, valor, descuento);

            lbl_ValorAPagar.setText(String.valueOf(men.getTotalIVA()));
        }
    }//GEN-LAST:event_btn_TotalConIVAActionPerformed

    private void TotalConDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalConDescuentoActionPerformed
      if (camposLLenos()) {
            String nombre = txt_Nombre.getText();
            int cantidad = Integer.parseInt(txt_Cantidad.getText());
            double descuento = Double.parseDouble(txt_descuento.getText());
            double valor = Double.parseDouble(txt_Valor.getText());
            Material men = new Material(nombre, cantidad, valor, descuento);

            lbl_ValorAPagar.setText(String.valueOf(men.getTotalDesc()));
        }
    }//GEN-LAST:event_TotalConDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TotalConDescuento;
    private javax.swing.JButton btn_TotalConIVA;
    private javax.swing.JButton btn_subtotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_Adv;
    private javax.swing.JLabel lbl_ValorAPagar;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Valor;
    private javax.swing.JTextField txt_descuento;
    // End of variables declaration//GEN-END:variables
}
